server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
prometheus:
  address: http://localhost:9090
  timeout: 1m
node_selectors:
  NVIDIA: gpu=on
  Ascend: ascend=on
  DCU: dcu=on
  MLU: mlu=on
  Metax: metax-tech.com/gpu.installed=true